### ISSUE TITLE
socket.computer isn't working

### ISSUE THREAD

**Issue by abhishek-kakkar** [kevin-roark/socket.io-computer#1]
This is what I get when I go to socket.computer: 

![screenshot from 2014-08-02 07 02 12](https://cloud.githubusercontent.com/assets/1833740/3786788/18f3b95a-19e5-11e4-8979-e142da3c31f8.png)

I don't know if this is expected.

**Comment by M132** [comment]
Someone suspended Windows and qemu is stuck in suspended state. Machine restarts every 15 mins anyways.
