### ISSUE TITLE
Issue: abuse

### ISSUE THREAD

**Issue by justinpage** [kevin-roark/socket.io-computer#4]
I was just curious if there is a safe-guard against people who create a new account, log-out, and then jump ship. I witnessed this just now and felt troubled how easy it was for the demo to be taking advantage of. 

Do you re-provision the windows install after so many hours, so as to account for those who abuse the demo?

![screenshot from 2015-01-08 17 01 49](https://cloud.githubusercontent.com/assets/3615935/5673991/6bbaceee-9758-11e4-843f-a6d1ab5d1f78.png)

**Comment by BitNetwork** [comment]
There actually is. The emulator restores a working snapshot every 15 minutes, therefore resetting all the user accounts created on it.
